config/routes.rb
Rails.application.routes.draw do
   root to: 'tops#index'
   # get 'sessions/new'
   resources :blogs do
  # comfirmのルーティン化
    collection do
      post :confirm
    end
  end
   resources :sessions, only: [:new, :create, :destroy]
   resources :users, only: [:new, :create, :show, :edit, :update]
# お気に入り
   resources :favorites
   # only: [:create, :destroy]
   mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  # validates :title, length: { in: 1..140 }
  # validates :content, length: { in: 1..140 }
  # user blogsアソシエーション紐づけ
  belongs_to :user
  # 多対多のアソシエーション
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  # 写真アップロード
  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
# user blogとの多対多のアソシエーション
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  # ユニーク制約：同メールアドレスで複数のユーザの保存を防ぐ
  validates :email, uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  # user blogsアソシエーション紐づけ
  has_many :blogs
  # 多対多のアソシエーション
  has_many :favorites, dependent: :destroy
  # 写真アップロード
  mount_uploader :image, ImageUploader
  # 画像がない場合のバリデーション
  validates :image, absence: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログイン機能
  protect_from_forgery with: :exception
  include SessionsHelper

  # ログイン無しユーザーをログインへ促す
  before_action :login_required
  
private
 def login_required
   redirect_to new_session_path unless current_user
 end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
  @blogs = Blog.all
  end
  def new
  @blog = Blog.new
  end
  def create
  @blog = current_user.blogs.build(blog_params)
  # @blog = Blog.new(blog_params)
  # @blog.user_id = current_user.id
  if params[:back]
      render :new
    elsif @blog.save
     # 追記 投稿後メール送信
     BlogMailer.blog_mail(@blog).deliver
     redirect_to blogs_path, notice: "ブログを作成しました！"
     else
     render :new
     end
  end
  def show
  # @blog = Blog.find(params[:id])
  # お気に入り機能
  @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  def edit
  # @blog = Blog.find(params[:id])
  end
  def update
   # @blog = Blog.find(params[:id])
   if @blog.update(blog_params)
     redirect_to blogs_path, notice: "ブログを編集しました！"
   elsif
     render :edit
   end
  end
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  def confirm
    @blog = current_user.blogs.build(blog_params)
    # @blog = Blog.new(blog_params)
    # @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  private
    def blog_params
     params.require(:blog).permit(:title, :content, :image, :image_cache)
    end
    def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
  def index
  @favorites = current_user.favorites
  # redirect_to favorites_path
  # @favorites = favorite.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
   session.delete(:user_id)
   flash[:notice] = 'ログアウトしました'
   redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :login_required, only: [:new, :create]
before_action :set_user, only: [:show, :edit, :update]
before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
    redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    # @user = User.find(params[:id])
  end

  # 追記
  def edit
    # @user = User.find(params[:id])

  end
  def update
    # @user = User.find(params[:id])
   if @user.update(user_params)
     redirect_to user_path(@user.id), notice: "プロフィールを編集しました！"
   else
     render :edit
   end
  end

  private
    def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation, :image,:image_cache)
    end
    def set_user
     @user = User.find(params[:id])
    end
    def correct_user
    if current_user.id != @user.id
    redirect_to user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end


end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
<!-- choose_new_or_editはヘルパーメソッドにて定義 -->
<% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <!-- 画像をアップロード -->
  <div class="field">
    <%= form.label :image %>
    <!-- 確認画面から新規作成画面に戻った時にアップロードした画像を表示させるための記述 -->
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to 'ブログ一覧画面に戻る',  blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<div class=name>
<p><%="#{@blog.user.name}さんのブログ"%></p>
</div>
<%= form_with(model: @blog, local: true, url: blogs_path ) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <!-- <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %> -->
  <%= form.hidden_field :image_cache %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p>Image:<%= image_tag @blog.image.url ,size: '50x50'%> </p>

  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>
<div class=name>
<p><%="#{@blog.user.name}さんのブログ"%></p>
</div>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<table>
  <tr>
    <th>ユーザー名</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>画像</th>

  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= "#{blog.user.name}さんのブログ" %></td>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= image_tag blog.image.url , size: '50x50'%></td>
    <td><%= link_to '【詳細を確認する】', blog_path(blog.id) %></td>

<!-- ログインユーザーのみ入力できる -->
    <% if current_user.id == blog.user.id %>
       <td><%= link_to '【ブログを編集する】', edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' }  %></td>
       <td><%= link_to '【ブログを削除する】', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= link_to '新規作成する', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<div class=name>
<p><%="#{@blog.user.name}さんのブログ"%></p>
</div>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image.url , size: '50x50' %>
</p>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to 'ブログ一覧画面に戻る',  blogs_path %>

app/views/favorites/index.html.erb
<h1>お気に入り</h1>

<table>
  <th>
    <tr>
      <th>ユーザー名</th>
      <th>タイトル</th>
      <th>内容</th>
      <th>画像</th>

    </tr>
  </th>

  <body>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.blog.user.name %></td>
        <td><%= favorite.blog.title %></td>
        <td><%= favorite.blog.content %></td>
        <td><%= image_tag favorite.blog.image.url, size: '50x50' %></td>
      </tr>
    <% end %>
  </body>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instoblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- スマホサイズの媒体に適用 -->
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <ul>
          <li><a>Instogram</a></li>
          <li>  <%= image_tag 'raion.jpg' ,size: '50x50'%></li>
          <li><a href="http://localhost:3000/">トップページ</a></li>
        </ul>
      </header>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
    <footer>
     <p>運営会社instogram株式会社</p>
     <p>© 2020-2021 in sto gram Corp.</p>
   </footer>
  </body>
</html>

app/views/tops/index.html.erb
<div class="container">
  <h1 class="title">Instogram</h1>

    <nav class="menu">
      <ul>
        <li>instoblogの世界へようこそ！</li>
      </ul>
    </nav>

<article>
  <div class="contents">
    <ul>
      <li>思い出を共有して、世界とつながろう！</li>
    </ul>
  </div>
  <div class="topic">
    <ul>
      <li></li>
    </ul>
  </div>
</article>

<%= link_to "instoblogを作成する", new_blog_path, class: 'btn btn-default' %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><!-- 改行 -->
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
<!-- 追記 -->
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/edit.html.erb
<h2>プロフィールを編集する</h2>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="top"><%= @user.name %>のページ</div>
<%= notice %>
<p>メールアドレス: <%= @user.email %></p>
  <p>
    <strong>プロフィール画像:</strong>
   <%= image_tag @user.image.url, size: '50x50' %>
   <%#=  @user.image %>
 </p>

<!-- 追加 他のユーザのプロフィールへいかないようにする-->
<% if current_user.id == @user.id %>
  <%= link_to 'お気に入り一覧', favorites_path %>
  <br>
  <%= link_to 'プロフィールを編集', edit_user_path(@user) %>

<% else %>
<h5>ユーザー：<%= @user.name %>を登録しました。</h5>
<h5><%= link_to "ログインに進む", new_session_path %></h5>
<% end %>

<br>
<%= link_to '新規作成する', new_blog_path %>
<br>
<%= link_to 'ブログ一覧画面に戻る',  blogs_path %>